name: Cypress run
on:
  pull_request
jobs:
  runTests:
    runs-on: ubuntu-20.04
    strategy:
      # when one test fails, DO NOT cancel the other
      fail-fast: false
      matrix:
        # run 5 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          browser: chrome
          group: 'Actions example'
        env:
          CYPRESS_RECORD_KEY: "a61edaed-2321-41d6-a74f-ed7a19327859"
          CYPRESS_PROJECT_ID: "54ysi7"

